config/routes.rb
Rails.application.routes.draw do
  get '/related_tags' => "articles#related_tags"
  root 'articles#index'
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :articles, only: [:show]

  get '/search' => "articles#search_page"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
# == Schema Information
#
# Table name: admin_users
#
#  id                     :bigint(8)        not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id                :bigint(8)        not null, primary key
#  title             :string(255)
#  body              :text(65535)
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  picture           :string(255)
#  category_id       :bigint(8)
#  desc              :text(65535)
#  impressions_count :integer          default(0)
#

class Article < ApplicationRecord
  # pv
  is_impressionable counter_cache: true

  # validation
  validates :title,       presence: true, length: { maximum: 40 }
  validates :body,        presence: true
  validates :category_id, presence: true

  # 画像アップ
  mount_uploader :picture, PictureUploader
  validate  :picture_size # カスタムバリデーション

  # アソシエーション
  belongs_to :category

  # タグ
  acts_as_taggable # Alias for acts_as_taggable_on :tags
  acts_as_taggable_on :label


  private

    # アップロードされた画像のサイズをバリデーションする
    def picture_size
      if picture.size > 1.megabytes
        errors.add(:picture, "1MB以下にしてください(容量設定可能)")
      end
    end

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :bigint(8)        not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ApplicationRecord
  has_many :articles
end

app/models/ckeditor/asset.rb
# == Schema Information
#
# Table name: ckeditor_assets
#
#  id                :integer          not null, primary key
#  data_file_name    :string(255)      not null
#  data_content_type :string(255)
#  data_file_size    :integer
#  type              :string(30)
#  width             :integer
#  height            :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
# == Schema Information
#
# Table name: ckeditor_assets
#
#  id                :integer          not null, primary key
#  data_file_name    :string(255)      not null
#  data_content_type :string(255)
#  data_file_size    :integer
#  type              :string(30)
#  width             :integer
#  height            :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
# == Schema Information
#
# Table name: ckeditor_assets
#
#  id                :integer          not null, primary key
#  data_file_name    :string(255)      not null
#  data_content_type :string(255)
#  data_file_size    :integer
#  type              :string(30)
#  width             :integer
#  height            :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Jpmobile::ViewSelector

  before_action :set_view_path


  private

  def set_view_path
    path =  request.smart_phone? ? 'smartphone' : ''
    prepend_view_path(Rails.root + 'app/views' + path)
    puts path
    puts "------------------------------------------------"
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # pvを取る
  # impressionist :actions=> [:show]

  def index
    # 暫定のもの　あとでカテゴリごとに最適かする

    @tags = ActsAsTaggableOn::Tag.most_used(30)

    @new_articles = Article.limit(100).order("created_at DESC")# 新着順のリスト

    # ピックアップ
    @articles = Article.all

    # pv順 現在はシンプルに合計pv数のみで抽出している
    @pv_articles = Article.order('impressions_count DESC').take(10)
      #日付で絞り込むなら以下のようにする
      # .where("? <= created_at", Time.now.yesterday)
      # .where("created_at <= ?", Time.now)

    @article_last1  = Article.last
    @article_last2 = Article.last(2)[0]

    @article_youtube = Article.first # 動画記事


    @osusume_articles = Article.last(5) # おすすめのロジック
    # @ranking_articles = Article.last(5) # ランキングのロジック

    @categories = Category.all

  end

  def show

    @article = Article.find(params[:id])
    @related_article = Article.all

    @osusume_articles = Article.last(5) # おすすめのロジック
    @ranking_articles = Article.last(5) # ランキングのロジック

    # 1記事に対して何人が見たのか
    impressionist(@article, nil, unique: [:session_hash])

  end

  def search_page

    @q = Article.search(search_params)
    @search_articles = @q.result#.page(params[:page]).per(30).order(created_at: :desc)#.eager_load(:taggings)

    @name = params[:q][:body_cont]
  end

  def related_tags
    # binding.pry
    @name = params[:format]
    @tags = Article.tagged_with(params[:format])
    # @tags
  end

private

  def search_params
    return {} if params[:q].blank?
    params.require(:q).permit(:title_cont,
                              :body_cont
                              )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def default_meta_tags
    {
      site: 'アプリ速報は流行や旬な話題をいち早く届けるメディアです',
      title: '流行をいち早くお届けするアプリ速報',
      reverse: true,
      viewport: "width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no",
      charset: 'utf-8',
      description: 'アプリ速報は旬な情報をお届けするウェブサイトです。あなたにとって素敵な情報が見つかると思いますよ。今すぐチェックしよう！',
      keywords: 'メディア, アプリ,流行, インスタ映え, インスタグラム, SNS,吉澤ひとみ, 大谷翔平,ハロウィン, クリスマス, 海外旅行, 高校生, 大学生 カップル, 彼女, 恋人, デートスポット, マッチング, 掲示板, ２チャンネル, LINE, FACEBOOK, TIKTOK',
      canonical: request.original_url,
      separator: '|',
      icon: [
        { href: image_url('icon.png') }, # TODO あとで設定
        { href: image_url('icon.png'), rel: 'apple-touch-icon', sizes: '180x180', type: 'image/png' },
      ],
      og: {
        site_name: 'アプリ速報',
        title: '流行や旬な話題をいち早く届けるメディアのアプリ速報です',
        description: 'あなたにとって素敵な情報が見つかると思いますよ。今すぐチェックしよう！',
        type: 'article',
        url: request.original_url,
        image: image_url('icon.png'), # TODO あとで設定
        locale: 'ja_JP',
      },
      fb: {
        app_id: '336855070210588'
      },
      twitter: {
        card: 'summary',
        site: '@appsoku',
      }
    }
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_osusume.html.erb
<div class="side-article-list border-left">
  <% @osusume_articles.each do |article| %>
  <!-- 記事を縦に10個くらい表示させる -->
  <!-- 写真 --><!-- 説明文 -->

  <div class="article-list-content">
    <div class="col-sm-3 col-xs-3">
      <div class="mini-img">
        <%= image_tag article.picture.url, :size => "65x55", class: 'side-img' if article&.picture %>
      </div>
    </div>
    <div class="col-sm-9 col-xs-9 erace-pl erace-pr">
      <div class="article-list-text">
        <%= link_to article.title.truncate(36), article_path(article) %>
      </div>
      <p>by Koki</p>
    </div>
  </div>
  <% end %>
</div>

app/views/articles/_ranking.html.erb
<!-- <div class="osusume">
  <h5 class="osusume-title">ランキング</h5>
  <p class="gray-text mini">テキストテキストテキストテキスト</p>
  <hr>
</div> -->

<div class="side-article-list border-left mb30">
  <% @pv_articles.each_with_index do |article, i| %>
  <!-- 記事を縦に10個くらい表示させる -->
  <!-- 写真 --><!-- 説明文 -->

  <div class="article-list-content">
    <div class="col-sm-3 col-xs-3">
      <div class="mini-img">
        <%= image_tag article.picture.url, :size => "65x55", class: 'side-img' if article&.picture %>
        <span class="icon_rank"><%= i + 1 %></span>
      </div>
    </div>
    <div class="col-sm-9 col-xs-9 erace-pl">
      <div class="article-list-text">
        <%= link_to article.title.truncate(36), article_path(article) %>
      </div>
      <p>by natsuki</p>
    </div>
  </div>
  <% end %>
</div>

app/views/articles/index.html.erb
<section class="pickup">
  <div class="container pt50 pb50">
    <div class="main_wrraper">
      <div class="tag center">
        <div class="col-sm-3">

        </div>
        <div class="col-sm-6 pb30">
          <h5>#タグ一覧</h5>
          <% @tags.each do |tag| %>
            <span class="popular_tag"><%= link_to tag.name, related_tags_path(tag.name), class: "tag-link" %>&nbsp;(<%= tag.taggings_count %>)</span>
          <% end %>
        </div>
        <div class="col-sm-3">

        </div>
      </div>
      <div class="col-sm-4 col-xs-12">
        <div class="main_background">
          <%= link_to @article_last1 do%>
            <p>記事1</p>
            <!-- 背景画像として扱うこともできることを考慮する -->
            <!-- <div class="eyecatch_instagram" style="background-image:url('https://www.instagram.com/p/BlncAuOAAP2/media/?size=m')"> </div> -->
            <%= image_tag @article_last1.picture.url, :size => "320x192", class: '' if @article_last1&.picture %>
            <h4 class="title-color"><%= @article_last1.title.truncate(30)%></h4>
            <p class="gray-text"><%== @article_last1.body.truncate(60)%></p>
            <!-- <p class="gray-text">公式ライター</p> -->
          <% end %>
        </div>
      </div>
      <div class="col-sm-4 col-xs-12 erace-pl">
        <div class="main_background">
          <%= link_to @article_last2 do%>
            <p>記事2</p>
            <%= image_tag @article_last2.picture.url, :size => "320x192", class: '' if @article_last2&.picture %>
            <h4 class="title-color"><%= @article_last2.title.truncate(30) %></h4>
            <p class="gray-text"><%= @article_last2.body.truncate(60) %></p>
            <p class="gray-text">Liam gallager</p>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-sm-4 col-xs-12 youtube_article center">
      <p>動画記事3</p>
      <iframe width="270" height="152" src="https://www.youtube.com/embed/t-YNqAoilZc?controls=0&amp;showinfo=0&amp;autoplay=0&amp;rel=0&amp;modestbranding=1&amp;mute=0&amp;autohide=1" frameborder="0" allowfullscreen=""></iframe>
      <!-- <div class="ytp-cued-thumbnail-overlay-image" style="background-image: url(&quot;https://i.ytimg.com/vi_webp/t-YNqAoilZc/hqdefault.webp&quot;);"></div> -->
      <h4 class="title-color"><%= @article_youtube.title.truncate(30) %></h4>
      <p class="gray-text"><%= @article_youtube.body.truncate(55) %></p>
    </div>
  </div>
</section>

<div class="container">

  <!-- 3カラム -->
  <div class="main pt20">
    <div class="col-sm-2 col-xs-12">
      <h4>カテゴリ</h4>
      <% @categories.each do |category| %>
        <p><%= link_to category.name %></p>
      <% end %>
      <%#= render 'ranking' %>

    </div>


    <div class="col-sm-6 col-xs-12">
      <h4>ピックアップ</h4>
      <% @articles.each do |article| %>
        <p><%= link_to article.title ,article_path(article) %></p>
      <% end %>

    </div>
    <div class="col-sm-4 col-xs-12 pb50">
      <h4 class="border-title">アクセスランキング</h4>
      <%= render 'ranking' %>


      <h4 class="border-title">おすすめ記事</h4>
      <%= render 'osusume' %>
    </div>

  </div>

</div>

<hr>

app/views/articles/related_tags.html.erb
<% breadcrumb :search_form %>



<div class="container">
  <div class="col-sm-8 col-xs-12">

    <h1>"<%= @name %>"に関連する検索結果 <%= @tags.count %>件</h1>

    <div class="article pb50">
      <% @tags.each do |article| %>

      <div class="created-time">
        記事作成 <%= article.created_at.strftime("%Y年 %m月 %d日") %>
      </div>
      <div class="article-title">
        <h1><%= article.title.truncate(40) %></h1>
      </div>


      <div class="article-body">
        <%== article.body.truncate(70) %>
      </div>

      <% end %>


    </div>

    <hr>

    <div class="related-article">
      <h4>関連する記事</h4>
      <hr>
    </div>

    <div class="ad-space">
      広告入ります
    </div>
  </div>





</div>

app/views/articles/search_page.html.erb
<% breadcrumb :search_form %>



<div class="container">
  <div class="col-sm-8 col-xs-12">

    <h1>"<%= @name %>"の検索結果 <%= @search_articles.size %>件</h1>

    <div class="article pb50">
      <% @search_articles.each do |article| %>

      <div class="created-time">
        記事作成 <%= article.created_at.strftime("%Y年 %m月 %d日") %>
      </div>
      <div class="article-title">
        <h1><%= article.title.truncate(40) %></h1>
      </div>


      <div class="article-body">
        <%== article.body.truncate(70) %>
      </div>

      <% end %>


    </div>

    <hr>

    <div class="related-article">
      <h4>関連する記事</h4>
      <hr>
    </div>

    <div class="ad-space">
      広告入ります
    </div>
  </div>





</div>

app/views/articles/show.html.erb
<% breadcrumb :show_article %>

<div class="container">
  <div class="col-sm-8 col-xs-12">

    <div class="article pb50">
      <div class="created-time">
        記事作成 <%= @article.created_at.strftime("%Y年 %m月 %d日") %>
      </div>
      <div class="article-title">
        <h1><%= @article.title %></h1>
      </div>

      <div class="pc-show-tags pt20">
        <% @article.label_list.each do |tag| %>
          <span class="popular_tag"><%= link_to tag, related_tags_path(tag), class: "tag-link" %>&nbsp;<%#= tag.taggings_count %></span>
        <% end %>
      </div>


      <div class="show-ad">
        広告
      </div>

      <div class="article-body">
        <%== auto_link(simple_format(@article.body), html: {target: '_blank'}) %>
      </div>

      <div class="show-ad">
        広告
      </div>

    </div>

    <hr>

    <div class="related-article">
      <h4>関連する記事</h4>
      <hr>

      <% @related_article.each do |article| %>
        <h4><%= link_to article.title, article_path(article) %></h4>
      <% end %>

    </div>
  </div>

  <div class="col-sm-4 col-xs-12 pl30 pb50">
    <div class="osusume">
      <h5 class="osusume-title">ランキング</h5>
      <p class="gray-text mini">テキストテキストテキストテキスト</p>
      <hr>
    </div>

    <!-- フィードはパーシャル化 -->
    <%= render 'ranking' %>

    <div class="ad-space">
      広告入ります
    </div>


    <div class="osusume mt30">
      <h5 class="osusume-title">おすすめの記事</h5>
      <p class="gray-text mini">注目されてる記事だよ</p>
      <hr>
    </div>
    <%= render 'osusume' %>

  </div>


</div>

<%# breadcrumb :show_article %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="bg-footer1 col-sm-12 col-xs-12 text-center">
    <div class="col-sm-3">
      <h5>カテゴリ一覧</h5>
      <p>美容</p>
      <p>ゲーム</p>
      <p>れのん</p>
      <p>ノエル</p>
      <p>アイス</p>
    </div>
    <div class="col-sm-3">
      <p>ビール</p>
      <p>夏フェス</p>
      <p>車</p>
      <p>スタバ</p>
    </div>
    <div class="col-sm-3">
      <p>お問い合わせ</p>
      <p>よくある質問</p>
      <p>利用規約</p>
      <p>運営会社</p>

    </div>
    <div class="col-sm-3">
      <p>Instagram</p>
      <p>Twitter</p>
      <p>Facebook</p>
      <p>Line</p>
    </div>
  </div>

  <div class="bg-footer2 col-sm-12 col-xs-12 text-center">
    Copyright (c) 2018 APPSOKU All Rights Reserved.
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header navbar-center">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand main-title" href="/">アプリ速報</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!-- <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li> -->
        <!-- <li><a href="#">Link</a></li> -->
        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li> -->
      </ul>

      <ul class="nav navbar-nav navbar-right">

        <form id="post_search" class="article_search navbar-form navbar-left" action="/search" accept-charset="UTF-8" method="get">
            <input name="utf8" type="hidden" value="✓">
          <p>
            <input placeholder="キーワード" type="text" name="q[body_cont]" id="q_body_cont">

            <input class="btn btn-default" name="commit" type="submit" value="検索" data-disable-with="検索!">
          </p>
        </form>

        <!-- <li class="dropdown"> -->

          <!-- <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">コンテンツ<span class="caret"></span></a> -->
          <!-- <ul class="dropdown-menu"> -->
            <!-- <li><a href="#">Action</a></li> -->
            <!-- <li><a href="#">Another action</a></li> -->
            <!-- <li><a href="#">Something else here</a></li> -->
            <!-- <li role="separator" class="divider"></li> -->
            <!-- <li><a href="#">Separated link</a></li> -->
          <!-- </ul> -->
        <!-- </li> -->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="google-site-verification" content="I9rnsEvEOCj_kJIhoCgjze2fzBecoNgOqjC2E7uhh08" />
    <%= analytics_init if Rails.env.production? %>
    <!-- meta_tagを最適化する -->
    <%= display_meta_tags(default_meta_tags) %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="bar-top">
      <div class="top-text">話題の情報をお届けします | アプ速</div>
    </div>
    <%= render 'layouts/header'  %>
    <%= breadcrumbs :class => "pan", semantic: true %>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% elsif alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer'%>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/smartphone/articles/index.html.erb
<!-- スマホ用HTML -->

<div class="container-fluid">

  <!-- main article -->
  <div class="img-wrapper">
    <%= link_to article_path(@article_last1) do %>
      <%= image_tag @article_last1.picture.url, width: "100%", height: "300px" %>
      <!-- 絶対位置でcss組んでいるため、注意 # TODO-->　
      <div class="absolute-text"><%= @article_last1.title %></div>
      <div class="absolute-text-pv"><%= @article_last1.impressionist_count %>views</div>
      <div class="absolute-text-author">author</div>
    <% end %>
  </div>


  <div class="separate container">
    <div class="tabnav row">
        <li class="col-xs-6 pl40 tab1"><a href="#tab01">新着の記事</a></li>
        <li class="col-xs-6 pl30 tab2"><a href="#tab02">人気の記事</a></li>
    </div>

    <div class="tabcontent">
      <div id="tab01">
        <% @new_articles.each do |article| %>
          <%= link_to article_path(article) do %>
            <li class="row list">
              <div class="col-xs-3 left-img pl30">
                <%= image_tag article.picture.url, :size => "70x70", class: 'list-img' %>
              </div>
              <div class="col-xs-9 right-content">
                <b class="list-title"><%= article.title.truncate(35) %></b>
                <div class="row pt30">
                  <div class="col-xs-3 pv-text">
                    <%= article.impressionist_count %>views
                  </div>
                  <div class="col-xs-6">

                  </div>
                  <div class="col-xs-3 author-text">
                    作者
                  </div>
                </div>
              </div>
            </li>
          <% end %>
        <% end %>
      </div>
      <div id="tab02">
        <!-- あとで人気ロジック作成する -->
        <% @pv_articles.each do |article| %>
          <%= link_to article_path(article) do %>
            <li class="row list">
              <div class="col-xs-3 left-img pl30">
                <%= image_tag article.picture.url, :size => "70x70", class: 'list-img' %>
              </div>
              <div class="col-xs-9 right-content">
                <b class="list-title"><%= article.title.truncate(35) %></b>
                <div class="row pt30">
                  <div class="col-xs-3 pv-text">
                    <%= article.impressionist_count %>views
                  </div>
                  <div class="col-xs-6">

                  </div>
                  <div class="col-xs-3 author-text">
                    作者
                  </div>
                </div>
              </div>
            </li>
          <% end %>
        <% end %>
      </div>
    </div>

  </div>
</div>

<!-- ページネーション -->

<!-- sns連携 -->


<!-- footer -->



<script type="text/javascript">
  jQuery(function($){
    $('.tabcontent > div').hide();

    $('.tabnav a').click(function () {
        $('.tabcontent > div').hide().filter(this.hash).fadeIn();

        $('.tabnav a').removeClass('active');
        $(this).addClass('active');

        return false;
    }).filter(':eq(0)').click();
  });
</script>

app/views/smartphone/articles/show.html.erb
<!-- 画像 -->
<div class="container-fluid">

  <!-- main article -->
  <div class="img-wrapper">
    <%= image_tag @article.picture.url, width: "100%", height: "300px" %>
  </div>

  <!-- 日時 -->
  <div class="created_at pl10 pt10">
    記事作成日: <%= @article.created_at.strftime("%Y年 %m月 %d日") %>
  </div>
  <!-- タイトル -->
  <div class="smt-show-title pl10 pt10 pr10">
    <h1 class="font26"><%= @article.title %></h1>
  </div>
  <div class="keywords pt10 pl20 pr20 none-style">
    <% @article.label_list.each do |tag| %>
      <%#= tag %>
      <span class="keyword"><%= link_to tag, related_tags_path(tag), class: "tag-link" %>&nbsp;<%#= @article.label.taggings_count %></span>
    <% end %>
  </div>

  <div class="show-pv right pl10 pt10 pr20">
    <p><%= @article.impressionist_count %>views</p>
  </div>

  <!-- SNS -->
  <div class="row pt10 pb20">
    <div class="col-xs-4 pl30">
      <a class="smt-line-logo" href="https://social-plugins.line.me/lineit/share?url=<%= request.url %>" target="_blank">LINE<%#= image_tag "line.png", :size => "100x90" %></a>
    </div>
    <div class="col-xs-4">
      <a class="smt-twitter-logo" href="https://twitter.com/share?url=<%= request.url %>&text=<%= @article.title %>" rel="nofollow" target="_blank">Twitter<%#= image_tag "twitter.png", :size => "100x90" %></a>
    </div>
    <div class="col-xs-3 pr20">
      <a class="smt-facebook-logo" href="https://www.facebook.com/sharer/sharer.php?u=<%= request.url %>" target="_blank">facebook<%#= image_tag "facebook.png", :size => "100x90" %></a>
    </div>
  </div>

  <!-- あらすじ -->
  <div class="top-desc">
    <!-- カラムを追加する -->
    <%= auto_link(simple_format(@article.desc), html: {target: '_blank'}) %>
  </div>

  <div class="ad-infeed">
    インフィード広告
  </div>

  <!-- <div class="mokuji">
    <h1 class="font16">このまとめ記事の目次</h1>
    <ul>
      <li>1. 横浜</li>
      <li>2. 野毛</li>
      <li>3. 伊勢佐木長者町</li>
      <li>4. 湘南台</li>
      <li>5. 鎌倉</li>
    </ul>
  </div> -->

  <div class="smt-main-article">
    <%== auto_link(simple_format(@article.body), html: {target: '_blank'}) %>
  </div>

  <div class="ad-square">
    ad
  </div>


</div>


<!-- 目次 -->

<!-- 本文 -->

<!-- 広告3つほど -->


<!-- 次のページ -->

<!-- 広告 -->

<!-- SNS -->

<!-- 関連するタグ -->

<!-- 横長広告 -->

<!-- 関連する記事のフィード -->

<!-- 横長広告 -->

<!-- おすすめまとめ記事 -->

<!-- キュレーター紹介 -->

<!-- 広告 -->

<!-- Footer -->
<!-- <div id="fb-root"></div>

<script>(function(d, s, id) {
var js, fjs = d.getElementsByTagName(s)[0];
if (d.getElementById(id)) return;
js = d.createElement(s); js.id = id;
js.src = 'https://connect.facebook.net/ja_JP/sdk.js#xfbml=1&version=v3.1&appId=336855070210588&autoLogAppEvents=1';
fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script> -->